@extends('admin.layout.layout')
@section('content')
<div class="app-content main-content"><div class="side-app"><div class="container-fluid main-container">
<div class="page-header"><div class="page-leftheader"><h4 class="page-title">Expenses</h4><p class="text-muted mb-0">Record business costs and see their effect on net profit.</p></div><div class="page-rightheader"><a data-ajax-page class="btn btn-outline-primary" href="{{ route('admin-orders.analytics') }}">Sales analytics</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card"><div class="card-body d-flex flex-wrap align-items-center justify-content-between gap-2"><div><b>Period:</b> {{ $periodLabel }}</div><div class="btn-group">@foreach(['today'=>'Today','month'=>'This month','year'=>'This year','all'=>'All time'] as $key=>$label)<a data-ajax-page class="btn btn-sm {{ $period===$key?'btn-primary':'btn-outline-primary' }}" href="{{ route('expenses.index',['period'=>$key]) }}">{{ $label }}</a>@endforeach</div></div></div>
<div class="row"><div class="col-xl-4"><div class="card"><div class="card-header"><h3 class="card-title">Add expense</h3></div><div class="card-body"><form data-purchase-form method="POST" action="{{ route('expenses.store') }}">@csrf<div class="mb-3"><label class="form-label">Category *</label><select class="form-select" name="category" required>@foreach($categories as $category)<option value="{{ $category }}">{{ ucfirst($category) }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Expense title *</label><input class="form-control" name="title" placeholder="Facebook ads, office rent" required></div><div class="mb-3"><label class="form-label">Amount *</label><input class="form-control" type="number" name="amount" min="0.01" step="0.01" required></div><div class="mb-3"><label class="form-label">Date *</label><input class="form-control" type="date" name="expense_date" value="{{ now()->toDateString() }}" required></div><div class="mb-3"><label class="form-label">Note</label><textarea class="form-control" name="note" rows="3"></textarea></div><button class="btn btn-primary w-100">Save expense</button></form></div></div><div class="card"><div class="card-header"><h3 class="card-title">{{ $periodLabel }} total</h3></div><div class="card-body"><h2 class="text-danger mb-3">৳{{ number_format($total,2) }}</h2>@foreach(['ads'=>'Ads','delivery'=>'Delivery','office'=>'Office','salary'=>'Salary','other'=>'Other'] as $key=>$label)<div class="expense-total"><span>{{ $label }}</span><b>৳{{ number_format((float)($byCategory[$key] ?? 0),2) }}</b></div>@endforeach</div></div></div>
<div class="col-xl-8"><div class="card"><div class="card-header"><h3 class="card-title">Expense records</h3></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="ps-4">Date</th><th>Category</th><th>Title / note</th><th class="text-end">Amount</th><th class="text-end pe-4">Action</th></tr></thead><tbody>@forelse($expenses as $expense)<tr><td class="ps-4">{{ $expense->expense_date->format('d M Y') }}</td><td><span class="badge bg-primary">{{ ucfirst($expense->category) }}</span></td><td><b>{{ $expense->title }}</b><small class="d-block text-muted">{{ $expense->note }}</small></td><td class="text-end text-danger">৳{{ number_format((float)$expense->amount,2) }}</td><td class="text-end pe-4"><a data-ajax-page class="btn btn-sm btn-outline-primary" href="{{ route('expenses.edit',$expense) }}">Edit</a><form data-purchase-form class="d-inline" method="POST" action="{{ route('expenses.destroy',$expense) }}" onsubmit="return confirm('Delete this expense?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-5">No expenses for this period.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $expenses->links() }}</div></div></div></div>
</div></div></div>
<style>.expense-total{display:flex;justify-content:space-between;padding:9px 0;border-top:1px solid rgba(130,140,160,.18)}</style>
@endsection
