@extends('admin.layout.layout')
@section('content')
<div class="app-content main-content"><div class="side-app"><div class="container-fluid main-container">
<div class="page-header"><div class="page-leftheader"><h4 class="page-title">Sales Analytics</h4><p class="text-muted mb-0">Product performance and recognized revenue</p></div><div class="page-rightheader"><a href="{{ route('admin-orders.index') }}" data-ajax-page class="btn btn-outline-primary">View all orders</a></div></div>
@php
$periods=['today'=>'Today','7_days'=>'Last 7 days','month'=>'This month','year'=>'This year','all'=>'All time'];
$statusColors=['pending'=>'warning','confirmed'=>'primary','processing'=>'info','shipped'=>'secondary','delivered'=>'success','cancelled'=>'danger'];
@endphp
<div class="card"><div class="card-body d-flex flex-wrap align-items-center justify-content-between gap-2 py-3"><div><b>Report period:</b> <span class="text-muted">{{ $periodLabel }}</span></div><div class="d-flex flex-wrap align-items-center gap-2"><div class="btn-group flex-wrap">@foreach($periods as $key=>$label)<a data-ajax-page href="{{ route('admin-orders.analytics',['period'=>$key,'per_page'=>request('per_page',15)]) }}" class="btn btn-sm {{ $period===$key?'btn-primary':'btn-outline-primary' }}">{{ $label }}</a>@endforeach</div><form method="GET" action="{{ route('admin-orders.analytics') }}" class="d-flex align-items-center gap-2" data-ajax-filter><input type="hidden" name="period" value="{{ $period }}"><label for="analytics-per-page" class="text-muted text-nowrap mb-0">Show</label><select id="analytics-per-page" name="per_page" class="form-select form-select-sm" data-ajax-filter-auto>@foreach([10,15,25,50] as $size)<option value="{{ $size }}" @selected((int)request('per_page',15)===$size)>{{ $size }}</option>@endforeach</select></form></div></div></div>
<div class="row">
@foreach([['Recognized revenue',$revenue,'currency','success'],['Completed sales',$orderCount,'number','primary'],['Units sold',$soldQuantity,'number','info'],['Average order value',$averageOrderValue,'currency','warning']] as [$label,$value,$format,$color])
<div class="col-12 col-sm-6 col-xl-3"><div class="card metric-card"><div class="card-body"><div class="d-flex justify-content-between"><div><p class="text-muted mb-2">{{ $label }}</p><h3 class="mb-0 text-{{ $color }}">@if($format==='currency')&#2547;{{ number_format((float)$value,2) }}@else{{ number_format((int)$value) }}@endif</h3></div><i class="metric-dot bg-{{ $color }}"></i></div></div></div></div>
@endforeach
</div>
<div class="row"><div class="col-xl-8"><div class="card"><div class="card-header"><div><h3 class="card-title mb-1">Top-selling products</h3><small class="text-muted">Product sales before order coupon and shipping adjustments</small></div></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="ps-4">#</th><th>Product</th><th class="text-center">Orders</th><th class="text-center">Units sold</th><th class="text-end pe-4">Product sales</th></tr></thead><tbody>
@forelse($topProducts as $product)<tr><td class="ps-4 text-muted">{{ $loop->iteration }}</td><td><div class="d-flex align-items-center gap-3"><div class="product-thumb">@if($product->image)<img src="{{ asset('admin/productimage/'.basename($product->image)) }}" alt="">@else<span>—</span>@endif</div><div><b>{{ $product->product_name }}</b><small class="d-block text-muted">Product ID: {{ $product->product_id ?: 'Deleted' }}</small></div></div></td><td class="text-center">{{ number_format($product->order_count) }}</td><td class="text-center fw-semibold">{{ number_format($product->units_sold) }}</td><td class="text-end pe-4 fw-semibold">&#2547;{{ number_format((float)$product->product_sales,2) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-5">No completed sales found for this period.</td></tr>@endforelse
</tbody></table></div><div class="px-4 py-3 border-top">{{ $topProducts->links() }}</div></div></div></div>
<div class="col-xl-4"><div class="card"><div class="card-header"><h3 class="card-title">Payment breakdown</h3></div><div class="card-body">@forelse($paymentBreakdown as $payment)<div class="breakdown-row"><div><b>{{ $payment->payment_method==='cod'?'Cash on delivery':'SSLCommerz' }}</b><small class="d-block text-muted">{{ number_format($payment->order_count) }} orders</small></div><strong>&#2547;{{ number_format((float)$payment->revenue,2) }}</strong></div>@empty<p class="text-muted mb-0">No payment data.</p>@endforelse</div></div>
<div class="card"><div class="card-header"><h3 class="card-title">All order statuses</h3></div><div class="card-body">@foreach(['pending','confirmed','processing','shipped','delivered','cancelled'] as $status)<div class="breakdown-row"><span><span class="badge bg-{{ $statusColors[$status] }} me-2">&nbsp;</span>{{ ucfirst($status) }}</span><b>{{ number_format((int)($statusBreakdown[$status]??0)) }}</b></div>@endforeach</div></div>
<div class="alert alert-light border"><b>Revenue rule</b><br><small>Paid online orders and delivered cash-on-delivery orders count. Cancelled and unpaid orders do not.</small></div></div></div>
</div></div></div>
<style>
.metric-card{min-height:120px}.metric-dot{width:12px;height:12px;border-radius:50%;box-shadow:0 0 0 6px rgba(90,100,220,.08)}.product-thumb{width:48px;height:48px;border:1px solid rgba(120,130,160,.2);border-radius:8px;display:grid;place-items:center;overflow:hidden;background:rgba(255,255,255,.04)}.product-thumb img{width:100%;height:100%;object-fit:contain}.breakdown-row{display:flex;align-items:center;justify-content:space-between;padding:12px 0;border-bottom:1px solid rgba(120,130,160,.18)}.breakdown-row:last-child{border-bottom:0}@media(max-width:575px){.btn-group .btn{margin-bottom:4px}.page-rightheader{margin-top:10px}}
</style>
@endsection